apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: graph-breaker
  namespace: graph-breaker
  labels:
    app: graph-breaker
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: registry.fedoraproject.org/fedora:32
    name: fedora
    referencePolicy:
      type: Local
  - from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/ubi
    name: ubi8
    referencePolicy:
      type: Source
  - name: src
    referencePolicy:
      type: Source
  - name: bin
    referencePolicy:
      type: Source
