apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: graph-breaker
  name: graph-breaker-src
  namespace: graph-breaker
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: graph-breaker:src
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/vrutkovs/graph-breaker
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: graph-breaker:ubi8
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - type: "GitHub"
    github:
      secret: "secret101"
