apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    image.openshift.io/triggers: |
      [
        {"from":{"kind":"ImageStreamTag","name":"graph-breaker:bin"},"fieldPath":"spec.template.spec.containers[?(@.name==\"graph-breaker\")].image"}
      ]
  labels:
    app: graph-breaker
  name: graph-breaker
  namespace: graph-breaker
spec:
  replicas: 1
  selector:
    deploymentconfig: graph-breaker
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: graph-breaker
        deploymentconfig: graph-breaker
    spec:
      containers:
        - image: ''
          imagePullPolicy: Always
          name: graph-breaker
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: graph-breaker-robot
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - graph-breaker
        from:
          kind: ImageStreamTag
          name: 'graph-breaker:bin'
      type: ImageChange
    - type: ConfigChange
